#!/usr/bin/env crystal
#
# Renders real dashboard frames into site/frames.js.
#
# The microsite does not use screenshots or hand-written mockups: it embeds the
# output of the actual widget code, rendered through the same CryTUI buffer the
# terminal draws, so the site cannot drift from what obsctl looks like. Run
# `make site-frames` after changing a widget or a theme.

require "./support/showcase"

module SiteFrames
  extend self

  # Themes shown in the site's switcher. The full set ships in the binary; this
  # is a spread of dark, light, and high-contrast palettes that reads well at a
  # glance.
  SHOWCASED = %w[ember slate tokyo-night catppuccin-mocha gruvbox synthwave-84 matrix github-light]

  WIDTH  = 118
  HEIGHT =  30

  def run : Nil
    frames = {} of String => Hash(String, String)

    SHOWCASED.each do |id|
      theme = Obsctl::TUI::Theme.by_id(id)
      buffer = render_frame(theme)
      ground = Showcase.swatch(theme.background, "#101010")
      # The whole palette travels with the frame: the site restyles itself from
      # these, so the page and the terminal in it are always the same theme.
      frames[id] = {
        "label"       => theme.label,
        "html"        => to_html(buffer, ground),
        "statsHtml"   => to_html(render_stats(theme), ground),
        "background"  => ground,
        "accent"      => Showcase.swatch(theme.accent, "#d97757"),
        "accentAlt"   => Showcase.swatch(theme.accent_alt, "#e8c59e"),
        "foreground"  => Showcase.swatch(theme.foreground, "#f0f0f0"),
        "muted"       => Showcase.swatch(theme.muted, "#8a867d"),
        "border"      => Showcase.swatch(theme.border, "#4a4640"),
        "borderFocus" => Showcase.swatch(theme.border_focus, "#d97757"),
        "success"     => Showcase.swatch(theme.success, "#87b37b"),
        "warning"     => Showcase.swatch(theme.warning, "#e0b44c"),
        "danger"      => Showcase.swatch(theme.danger, "#e06c5f"),
        "info"        => Showcase.swatch(theme.info, "#7ba9c7"),
      }
    end

    path = File.expand_path("../site/frames.js", __DIR__)
    File.write(path, String.build do |io|
      io << "// Generated by scripts/render_site_frames.cr -- do not edit by hand.\n"
      io << "// Rendered from the real widget code; regenerate with `make site-frames`.\n"
      io << "window.OBSCTL_FRAMES = "
      frames.to_json(io)
      io << ";\n"
    end)

    STDOUT.puts "wrote #{path} (#{SHOWCASED.size} themes, #{WIDTH}x#{HEIGHT})"
  end

  private def render_frame(theme : Obsctl::TUI::Theme) : CryTUI::Buffer
    model = Showcase.model(theme)
    buffer = CryTUI::Buffer.new(CryTUI::Rect.new(0, 0, WIDTH, HEIGHT))
    Obsctl::TUI::Widgets::Dashboard.render(buffer.area, buffer, model)
    buffer
  end

  # The stream health panel on its own, for the section that explains it.
  private def render_stats(theme : Obsctl::TUI::Theme) : CryTUI::Buffer
    model = Showcase.model(theme)
    buffer = CryTUI::Buffer.new(CryTUI::Rect.new(0, 0, 49, 7))
    Obsctl::TUI::Widgets::Stats.render(buffer.area, buffer, model)
    buffer
  end

  # Serialises a rendered buffer as HTML, collapsing runs of identically styled
  # cells into one span so the payload stays small.
  #
  # A terminal cell is a fixed box; a browser glyph is not. An emoji occupies
  # exactly two cells here but renders at whatever advance the colour-emoji
  # font happens to use, and `⏱` is one cell but is often given emoji
  # presentation at roughly two. Either way the rest of the row slides out of
  # the character grid and the panels stop lining up with each other.
  #
  # So every run containing a non-ASCII glyph is emitted as an inline-block of
  # exactly as many `ch` as it occupies cells. ASCII needs no such box: in a
  # monospace face it is already one advance per character.
  private def to_html(buffer : CryTUI::Buffer, ground : String) : String
    String.build do |io|
      (0...buffer.area.height).each do |row|
        io << "<span class=\"row\">"
        run = String::Builder.new
        run_css = nil.as(String?)
        run_ascii = true
        run_cells = 0
        emitted = 0

        flush = -> do
          text = run.to_s
          unless text.empty?
            style = run_css
            if run_ascii
              if style
                io << "<span style=\"" << style << "\">" << Showcase.escape(text) << "</span>"
              else
                io << Showcase.escape(text)
              end
            else
              io << "<span class=\"g\" style=\"width:" << run_cells << "ch"
              io << ';' << style if style
              io << "\">" << Showcase.escape(text) << "</span>"
            end
            emitted += run_cells
          end
          run = String::Builder.new
          run_cells = 0
        end

        (0...buffer.area.width).each do |column|
          cell = buffer[buffer.area.x + column, buffer.area.y + row]
          next if cell.continuation?

          symbol = cell.symbol.empty? ? " " : cell.symbol
          css = cell_css(cell, ground)
          ascii = symbol.ascii_only?
          flush.call if css != run_css || ascii != run_ascii
          run_css = css
          run_ascii = ascii
          run_cells += {CryTUI::TextWidth.width(symbol), 1}.max
          run << symbol
        end

        flush.call

        # The grid is the whole point: if a row does not declare exactly the
        # buffer's width, something above is wrong and the panels would drift.
        raise "row #{row} spans #{emitted} cells, expected #{buffer.area.width}" unless emitted == buffer.area.width

        # No newline: `.row` is a block element and already breaks the line.
        # A literal newline here lands inside `white-space: pre` and renders as
        # a second, blank line under every row.
        io << "</span>"
      end
    end
  end

  private def cell_css(cell : CryTUI::Cell, ground : String) : String?
    style = cell.style
    foreground = style.foreground
    background = style.background
    foreground, background = background, foreground if style.modifiers.reversed?

    declarations = [] of String
    if color = foreground.try { |value| Showcase.css_color(value) }
      declarations << "color:#{color}"
    end
    # The dashboard paints the theme background onto every cell, but the frame
    # already sits on it. Repeating it per cell makes each row an opaque strip
    # that paints over the descenders hanging down from the row above, which
    # reads as text clipped along its baseline. Only a genuine highlight -- a
    # selected row, a badge -- gets a background of its own.
    if (color = background.try { |value| Showcase.css_color(value) }) && color != ground
      declarations << "background:#{color}"
    end
    declarations << "font-weight:700" if style.modifiers.bold?
    declarations << "font-style:italic" if style.modifiers.italic?
    declarations << "text-decoration:underline" if style.modifiers.underlined?
    declarations << "opacity:.65" if style.modifiers.dim?

    declarations.empty? ? nil : declarations.join(";")
  end
end

SiteFrames.run
