#!/usr/bin/env crystal
#
# Renders real dashboard frames into site/frames.js.
#
# The microsite does not use screenshots or hand-written mockups: it embeds the
# output of the actual widget code, rendered through the same CryTUI buffer the
# terminal draws, so the site cannot drift from what obsctl looks like. Run
# `make site-frames` after changing a widget or a theme.

require "../src/obsctl/tui/widgets/dashboard"

module SiteFrames
  extend self

  # Themes shown in the site's switcher. The full set ships in the binary; this
  # is a spread of dark, light, and high-contrast palettes that reads well at a
  # glance.
  SHOWCASED = %w[ember slate tokyo-night catppuccin-mocha gruvbox synthwave-84 matrix github-light]

  WIDTH  = 118
  HEIGHT =  36

  # The 16 ANSI colours, for the one built-in theme that uses indexed colours.
  INDEXED = {
    0 => "#1c1c1c", 1 => "#d64545", 2 => "#4fb477", 3 => "#d6a544",
    4 => "#4f8ed6", 5 => "#b46fd6", 6 => "#4fc3d6", 7 => "#c8c8c8",
    8 => "#6a6a6a", 9 => "#ff6b6b", 10 => "#6fe3a0", 11 => "#ffd166",
    12 => "#6fb2ff", 13 => "#d29bff", 14 => "#6fe6ff", 15 => "#f5f5f5",
  }

  def run : Nil
    frames = {} of String => Hash(String, String)

    SHOWCASED.each do |id|
      theme = Obsctl::TUI::Theme.by_id(id)
      buffer = render_frame(theme)
      # The whole palette travels with the frame: the site restyles itself from
      # these, so the page and the terminal in it are always the same theme.
      frames[id] = {
        "label"       => theme.label,
        "html"        => to_html(buffer),
        "statsHtml"   => to_html(render_stats(theme)),
        "background"  => swatch(theme.background, "#101010"),
        "accent"      => swatch(theme.accent, "#d97757"),
        "accentAlt"   => swatch(theme.accent_alt, "#e8c59e"),
        "foreground"  => swatch(theme.foreground, "#f0f0f0"),
        "muted"       => swatch(theme.muted, "#8a867d"),
        "border"      => swatch(theme.border, "#4a4640"),
        "borderFocus" => swatch(theme.border_focus, "#d97757"),
        "success"     => swatch(theme.success, "#87b37b"),
        "warning"     => swatch(theme.warning, "#e0b44c"),
        "danger"      => swatch(theme.danger, "#e06c5f"),
        "info"        => swatch(theme.info, "#7ba9c7"),
      }
    end

    path = File.expand_path("../site/frames.js", __DIR__)
    File.write(path, String.build do |io|
      io << "// Generated by scripts/render_site_frames.cr -- do not edit by hand.\n"
      io << "// Rendered from the real widget code; regenerate with `make site-frames`.\n"
      io << "window.OBSCTL_FRAMES = "
      frames.to_json(io)
      io << ";\n"
    end)

    STDOUT.puts "wrote #{path} (#{SHOWCASED.size} themes, #{WIDTH}x#{HEIGHT})"
  end

  # Builds a model holding the state a busy stream would actually be in, so the
  # frame shows every panel doing something rather than an empty shell.
  private def showcase_model(theme : Obsctl::TUI::Theme) : Obsctl::TUI::Model
    model = Obsctl::TUI::Model.new(theme: theme)
    model.connected_to_daemon = true
    model.snapshot = Obsctl::OBS::State::ObsSnapshot.new(
      connected: true,
      obs_studio_version: "31.0.0",
      obs_websocket_version: "5.5.0",
      current_scene: "Main Camera",
      scenes: [
        Obsctl::OBS::State::SceneState.new("Main Camera", alias: "main", shortcut: "1", group: "Live", active: true),
        Obsctl::OBS::State::SceneState.new("Screen Share", alias: "screen", shortcut: "2", group: "Live"),
        Obsctl::OBS::State::SceneState.new("Guest Cam", alias: "guest", shortcut: "3", group: "Live"),
        Obsctl::OBS::State::SceneState.new("BRB", alias: "brb", shortcut: "4", group: "Breaks"),
        Obsctl::OBS::State::SceneState.new("Starting Soon", alias: "soon", shortcut: "5", group: "Breaks"),
      ],
      audio_inputs: [
        Obsctl::OBS::State::AudioState.new("Mic/Aux", alias: "mic", shortcut: "m", muted: false, volume_mul: 0.72, volume_db: -4.2, volume_percent: 72),
        Obsctl::OBS::State::AudioState.new("Desktop Audio", alias: "desktop", shortcut: "d", muted: false, volume_mul: 0.48, volume_db: -8.1, volume_percent: 48),
        Obsctl::OBS::State::AudioState.new("Guest Line", alias: "guest", muted: true, volume_mul: 0.6, volume_db: -6.0, volume_percent: 60),
      ],
      output: Obsctl::OBS::State::OutputState.new(streaming: true, recording: true),
      profiles: ["Default", "Streaming", "Recording HQ"],
      current_profile: "Streaming",
      scene_collections: ["Podcast", "Gaming", "Interview"],
      current_scene_collection: "Gaming",
      stats: Obsctl::OBS::State::ObsStats.new(
        cpu_usage_percent: 3.2,
        memory_usage_mb: 742.0,
        available_disk_space_mb: 512_000.0,
        active_fps: 59.94,
        average_frame_render_time_ms: 1.42,
        render_skipped_frames: 12_i64,
        render_total_frames: 128_400_i64,
        output_skipped_frames: 340_i64,
        output_total_frames: 128_000_i64
      ),
      stream_bitrate_kbps: 5_842.0,
      stream_duration_ms: 4_215_000_i64,
      record_duration_ms: 4_215_000_i64
    )
    model.meter_levels["Mic/Aux"] = 0.62
    model.meter_levels["Desktop Audio"] = 0.24
    model.cpu_history = [2.1, 2.8, 3.6, 3.1, 2.9, 3.4, 4.0, 3.2, 2.7, 3.2]
    model.bitrate_history = [5_600.0, 5_720.0, 5_500.0, 5_842.0, 5_900.0, 5_780.0, 5_842.0]
    model.fps_history = [59.94, 59.94, 58.6, 59.94, 59.94, 59.9, 59.94, 59.94]
    model.anim.frame = 7_u64

    [
      {Obsctl::Runtime::LogLevel::Info, "connected to OBS 31.0.0", "obs_connected"},
      {Obsctl::Runtime::LogLevel::Info, "stream started -> 'Main Camera'", "obs_event"},
      {Obsctl::Runtime::LogLevel::Info, "profile switched -> Streaming", "obs_event"},
      {Obsctl::Runtime::LogLevel::Warn, "reconnect attempt 1 scheduled in 500ms", "obs_reconnect"},
      {Obsctl::Runtime::LogLevel::Info, "scene set: Main Camera", "command_ok"},
    ].each_with_index do |(level, message, code), index|
      model.push_log(Obsctl::TUI::LogEntry.new(level, message, code, Time.utc(2026, 8, 1, 21, 14, index * 7 + 2)))
    end

    model
  end

  private def render_frame(theme : Obsctl::TUI::Theme) : CryTUI::Buffer
    model = showcase_model(theme)
    buffer = CryTUI::Buffer.new(CryTUI::Rect.new(0, 0, WIDTH, HEIGHT))
    Obsctl::TUI::Widgets::Dashboard.render(buffer.area, buffer, model)
    buffer
  end

  # The stream health panel on its own, for the section that explains it.
  private def render_stats(theme : Obsctl::TUI::Theme) : CryTUI::Buffer
    model = showcase_model(theme)
    buffer = CryTUI::Buffer.new(CryTUI::Rect.new(0, 0, 49, 7))
    Obsctl::TUI::Widgets::Stats.render(buffer.area, buffer, model)
    buffer
  end

  # Serialises a rendered buffer as HTML, collapsing runs of identically styled
  # cells into one span so the payload stays small.
  private def to_html(buffer : CryTUI::Buffer) : String
    String.build do |io|
      (0...buffer.area.height).each do |row|
        io << "<span class=\"row\">"
        run = String::Builder.new
        run_css = nil.as(String?)

        flush = -> do
          text = run.to_s
          unless text.empty?
            if css = run_css
              io << "<span style=\"" << css << "\">" << escape(text) << "</span>"
            else
              io << escape(text)
            end
          end
          run = String::Builder.new
        end

        (0...buffer.area.width).each do |column|
          cell = buffer[buffer.area.x + column, buffer.area.y + row]
          next if cell.continuation?
          css = cell_css(cell)
          if css != run_css
            flush.call
            run_css = css
          end
          run << (cell.symbol.empty? ? " " : cell.symbol)
        end

        flush.call
        io << "</span>\n"
      end
    end
  end

  # The MONO theme is built from ANSI indices rather than hex, so a palette
  # entry can resolve to nothing renderable; callers supply the fallback.
  private def swatch(color : CryTUI::Color, fallback : String) : String
    css_color(color) || fallback
  end

  private def cell_css(cell : CryTUI::Cell) : String?
    style = cell.style
    foreground = style.foreground
    background = style.background
    foreground, background = background, foreground if style.modifiers.reversed?

    declarations = [] of String
    if color = foreground.try { |value| css_color(value) }
      declarations << "color:#{color}"
    end
    if color = background.try { |value| css_color(value) }
      declarations << "background:#{color}"
    end
    declarations << "font-weight:700" if style.modifiers.bold?
    declarations << "font-style:italic" if style.modifiers.italic?
    declarations << "text-decoration:underline" if style.modifiers.underlined?
    declarations << "opacity:.65" if style.modifiers.dim?

    declarations.empty? ? nil : declarations.join(";")
  end

  # Nil for `Reset`, which inherits whatever the page already has.
  private def css_color(color : CryTUI::Color) : String?
    case color.kind
    when .rgb?     then "#%02x%02x%02x" % {color.red, color.green, color.blue}
    when .indexed? then INDEXED[color.index.to_i]? || "#c8c8c8"
    end
  end

  private def escape(text : String) : String
    text.gsub('&', "&amp;").gsub('<', "&lt;").gsub('>', "&gt;")
  end
end

SiteFrames.run
