#!/usr/bin/env crystal
#
# Exports real theme palettes into site/themes.js.
#
# The microsite's switcher restyles the page from obsctl's own palettes rather
# than from colours re-typed into the stylesheet, so the page and the product
# can never drift apart. The palettes are read out of `Obsctl::TUI::Theme`, the
# same constant the binary paints from. Run `make site-themes` after changing a
# theme.
#
# The dashboard itself is not rendered here any more: the site shows the
# recording in docs/demo/obsctl.cast instead of a still frame.

require "json"
require "../src/obsctl/tui/theme"

module SiteThemes
  extend self

  # Themes offered in the site's switcher. The full set ships in the binary;
  # this is a spread of dark, light, and high-contrast palettes that reads well
  # at a glance.
  SHOWCASED = %w[ember slate tokyo-night catppuccin-mocha gruvbox synthwave-84 matrix github-light]

  # The 16 ANSI colours, for the one built-in theme that uses indexed colours.
  INDEXED = {
    0 => "#1c1c1c", 1 => "#d64545", 2 => "#4fb477", 3 => "#d6a544",
    4 => "#4f8ed6", 5 => "#b46fd6", 6 => "#4fc3d6", 7 => "#c8c8c8",
    8 => "#6a6a6a", 9 => "#ff6b6b", 10 => "#6fe3a0", 11 => "#ffd166",
    12 => "#6fb2ff", 13 => "#d29bff", 14 => "#6fe6ff", 15 => "#f5f5f5",
  }

  def run : Nil
    themes = {} of String => Hash(String, String)

    SHOWCASED.each do |id|
      theme = Obsctl::TUI::Theme.by_id(id)
      themes[id] = {
        "label"       => theme.label,
        "background"  => swatch(theme.background, "#101010"),
        "accent"      => swatch(theme.accent, "#d97757"),
        "accentAlt"   => swatch(theme.accent_alt, "#e8c59e"),
        "foreground"  => swatch(theme.foreground, "#f0f0f0"),
        "muted"       => swatch(theme.muted, "#8a867d"),
        "border"      => swatch(theme.border, "#4a4640"),
        "borderFocus" => swatch(theme.border_focus, "#d97757"),
        "success"     => swatch(theme.success, "#87b37b"),
        "warning"     => swatch(theme.warning, "#e0b44c"),
        "danger"      => swatch(theme.danger, "#e06c5f"),
        "info"        => swatch(theme.info, "#7ba9c7"),
      }
    end

    path = File.expand_path("../site/themes.js", __DIR__)
    File.write(path, String.build do |io|
      io << "// Generated by scripts/render_site_themes.cr -- do not edit by hand.\n"
      io << "// Read from the real theme table; regenerate with `make site-themes`.\n"
      io << "window.OBSCTL_THEMES = "
      themes.to_json(io)
      io << ";\n"
    end)

    STDOUT.puts "wrote #{path} (#{SHOWCASED.size} themes)"
  end

  # The MONO theme is built from ANSI indices rather than hex, so a palette
  # entry can resolve to nothing renderable; callers supply the fallback.
  private def swatch(color : CryTUI::Color, fallback : String) : String
    css_color(color) || fallback
  end

  # Nil for `Reset`, which inherits whatever the page already has.
  private def css_color(color : CryTUI::Color) : String?
    case color.kind
    when .rgb?     then "#%02x%02x%02x" % {color.red, color.green, color.blue}
    when .indexed? then INDEXED[color.index.to_i]? || "#c8c8c8"
    end
  end
end

SiteThemes.run
